### ISSUE TITLE
Running Windows exe only creates this log file 

### ISSUE THREAD

**Issue by JFMugen** [thevindu-w/clip_share_server#2]
"Can't bind to port 4337 UDP" 

Tried to create a new inbound/outbound rule in Firewall but didn't help :/

**Comment by thevindu-w** [comment]
This probably happens when another instance of the program is running and using the same port. A port can be used by only one process at a time. You can fix it in any of the following ways,
- Open the task manager in Windows and stop the clip_share process and re-run the app.
- Using the command line argument -s to stop the app and start it again. (you can do this in the command prompt, PowerShell, or any other shell by running the command `./clip_share.exe`)
- Wait for a few days and get the newest version (I haven't released this yet) which is restarting by default. Then you have to just double-click on it to run. It will stop the currently running instances by itself.
<br>
<br>
If the UDP port 4337 is used by some other app, the above solutions may not work. If that is the case, you can check which app is using that port by running the following command in a command prompt or a PowerShell (you may need to open the command prompt or PowerShell as admin).
<br>
netstat -a -b
<br>
You will see a list of apps using various ports. Look for `4337` in that list and see which app is using that port. If you do not need that application to run, you can stop that (and stop any other instances of clip_share as well). Then, re-run clip_share.exe.
<br>
<br>
If that didn't work, please don't hesitate to ask for further help.

**Comment by JFMugen** [comment]
Hmm, looks like the reason was having more than one instance. When I just click once, there is no log file. 

But I couldn't manage to connect, which might be my lack of knowledge. On phone I just write the number than I use for connecting my modem (192.168.1.1) and then I tried the default thing in the app (192.168.1.2) but both of them result "No Servers Found". I am not sure what I am doing wrong, but maybe a tutorial can be helpful for more clueless users :)

**Comment by thevindu-w** [comment]
> When I just click once, there is no log file.

Yes, that's the expected behavior of the app. Note that it doesn't open any visible window. It runs in the background.

> On phone I just write the number that I use for connecting my modem (192.168.1.1)

No, this is the IP address of the modem. You should use the IP address of your laptop (or desktop) computer.
<br>
First make sure the following things are correctly set up.
- Both the phone and the laptop or desktop computer are connected to the same Wi-Fi network (or the computer is connected to the mobile hotspot of your phone)
- The server is allowed through the firewall. If you just double-clicked on the exe file, Windows Defender firewall should pop-up and ask to allow or block, where you have to allow. Otherwise you can go to the firewall settings and allow it manually. Please refer to the README.md file for the Allow through firewall section for more details. If you are using any other anti-virus software, it may also have a firewall. Whitelist the app if there are any such firewalls in your system.
- You have not changed the port numbers in the clipshare.conf file. If you don't have a clipshare.conf file or you got the clipshare.conf file from the releases or README, it should have 4337 as the port. But probably this is not the issue in your situation.
- Though it's unlikely, your phone may have a firewall, proxy, VPN, other network setting that routes the local network traffic through a different path. If you haven't installed such applications, you can ignore this.
<br>
To find the IP address of your computer, you can use any of the following methods,

- If you are using my android app, you can use the scan button. You need the server running on your computer for the scan to work.
- Using the `ipconfig` command in a command prompt. Note that you should use the `IPv4 Address`, not the IPv6 address, Default gateway, or the subnet mask.
- Viewing the IP address in Settings > Network and Internet > View your network properties.

The IP address should look like 192.168.1.\<some number\> where \<some number\> is not 1 (which is the IP address of the router as you mentioned).

**Comment by thevindu-w** [comment]
> On phone I just write the number that I use for connecting my modem (192.168.1.1) and then I tried the default number in the app (192.168.1.2) but both of them result "No Servers Found".

The scan button is there in the Android app to find the server automatically. If you manually put the IP address, you don't need to scan again.

Once you have the IP address entered in the client app (mobile), you can check it by copying some text on your computer and then pressing the `GET` button on the Android client app. If you see the copied text on the mobile app, it is working. Then, you should be able to paste it on any other place in your mobile (it gets copied into the clipboard when you press the `GET` button).

> maybe a tutorial can be helpful for more clueless users :)

Yes, this looks like a good idea. I'll try to make a tutorial.

**Comment by JFMugen** [comment]
>Yes, that's the expected behavior of the app. Note that it doesn't open any visible window. It runs in the background.

I was expecting a GUI so clicked several times, my bad there. 

Other than that, I couldn't make it work :/ 

>Both the phone and the laptop or desktop computer are connected to the same Wi-Fi network (or the computer is connected to the mobile hotspot of your phone)

Done. 

>The server is allowed through the firewall. 

Done.
![image](https://github.com/thevindu-w/clip_share_server/assets/61559703/ff6fae60-f124-4551-8f68-02c202ea065a)

You have not changed the port numbers in the clipshare.conf file. If you don't have a clipshare.conf file..

I don't have the file. 

>Though it's unlikely, your phone may have a firewall, proxy, VPN, other network setting

Not that I know of. Any way I can verify this? I know for sure that I haven't installed any app that should affect the network.

///

>If you are using my android app, you can use the scan button. You need the server running on your computer for the scan to work.

Sadly doesn't work :/ 

>Once you have the IP address entered in the client app (mobile), you can check it by copying some text on your computer and then pressing the GET button 

Gives "Couldn't Connect" error. 

I believe everything should be good but looks like it isn't? Idk :/

**Comment by thevindu-w** [comment]
> Gives "Couldn't Connect" error.

Are both devices (computer and mobile) on the same WiFi network?
Did you find the correct IP address of the server?
And, did you copied some text on the computer before pressing the GET button on mobile?

**Comment by JFMugen** [comment]
Alriiiight, I just thought about trying with mobile hotspot and worked instantly. So I think the program works as intended. 

But I have no idea what might be the difference between that and my wi-fi

>Are both devices (computer and mobile) on the same WiFi network?

Yep

>Did you find the correct IP address of the server?

From ipconfig -> 
![image](https://github.com/thevindu-w/clip_share_server/assets/61559703/6f4a9e98-d781-4719-9ad6-c2b461886958)

>And, did you copied some text on the computer before pressing the GET button on mobile?

Yep

**Comment by thevindu-w** [comment]
Now that implies both the server and client are working, but the network was the problem.

Is that IP address, which you found through ipconfig, is the IP address when you connect to the WiFi? or is it the IP address when connected to the mobile hotspot?
That IP address looks correct. If the IP address is not the problem, then probably the firewall may be blocking the app. Please check the firewall rules to see if it allows connections
- from any Source IP
- to any Destination IP
- on both protocols TCP and UDP
- to port 4337 (or allowing to any port)

**Comment by JFMugen** [comment]
>Is that IP address, which you found through ipconfig, is the IP address when you connect to the WiFi?

Yep, hotspot was different. 

>then probably the firewall may be blocking the app

Well, now it works. I have no idea whether I didn't see before (I don't think so?) or they appear after trying with hotspot, but I see these 2 now. 

![image](https://github.com/thevindu-w/clip_share_server/assets/61559703/386f0ebd-3fc8-448f-a1bb-3b52e3bf04a7)

They were "Block" and after disabling both, now it works as intended.

**Comment by thevindu-w** [comment]
Great. As I see, the new rules are for public networks. I guess the issue was private vs public networks. If it's now working properly on both networks, we can close this issue.
If you have any further doubts, feel free to ask.

**Comment by JFMugen** [comment]
> I guess the issue was private vs public networks.

The screenshot I send above and the last one both "All" actually, I changed them to all myself before you say it, thinking it might be the problem, but it didn't help. 

I really have no idea why these 2 appear to be honest but either way the issue was on my side for sure. Thanks for the help and I hope it can help some others as well in future ^^

**Comment by JFMugen** [comment]
@thevindu-w 

>Wait for a few days and get the newest version

Just thought about it but how about just creating a tray icon when it is active? I don't know if it is hard to implement but it would be useful for sure.

**Comment by thevindu-w** [comment]
Yes, It's a good idea. I'll try to do that. It's good to have some kind of an indicator.

**Comment by thevindu-w** [comment]
Feature to create a tray icon on Windows is now available in the master branch if you want to compile it yourself. It will be included in the next release v2.2 in a few days.

**Comment by JFMugen** [comment]
> Feature to create a tray icon on Windows is now available in the master branch if you want to compile it yourself. It will be included in the next release v2.2 in a few days.

Thanks for the heads-up but I am not very experienced with compiling and stuff, I will wait for the release ^^

**Comment by thevindu-w** [comment]
@JFMugen Version 2.2 with Windows tray icon support is now available as a [release](https://github.com/thevindu-w/clip_share_server/releases/v2.2).

**Comment by JFMugen** [comment]
Hey, works great ^^ 

But I just think you should add "Right Click -> Exit" option to the tray icon. I don't think any more than "Exit" is needed.

**Comment by thevindu-w** [comment]
Ok I'll try to include it in the next release

**Comment by JFMugen** [comment]
@thevindu-w btw just letting you know that sometimes it doesn't create an icon. I tried yesterday and saw the icon but today it doesn't appear. All I did was moving the file from C/Downloads to E/_Portable Tools, feel free to tell me if there is anything else I can provide like log etc.

**Comment by thevindu-w** [comment]
> sometimes it doesn't create an icon.

Is the server running when the icon is not displayed? You can check if it's running from the task manager.

> All I did was moving the file from C/Downloads to E/_Portable Tools.

Does the tray icon **always** work when it's in C:\?
Does the tray icon **sometimes** work when it's in E:\?

**Comment by JFMugen** [comment]
>Is the server running even when the icon is not displayed? You can check if it's running from the task manager.

Yep, I was sure it was working from task manager 

>Does the tray icon always work when it's in C:?
>Does the tray icon sometimes work when it's in E:?

Right now it doesn't show at all whether its C or E -_-  

![image](https://github.com/thevindu-w/clip_share_server/assets/61559703/61980f63-0e2b-44c6-bcbd-d40e7fff0987)

**Comment by thevindu-w** [comment]
> Right now it doesn't show at all whether its C or E -_-

Try to stop all ClipShare processes and re-run it.
May be the existing process is removing the tray icon. I have to check that.

**Comment by JFMugen** [comment]
>Try to stop all ClipShare processes and re-run it.

Tried it, restarted PC as well to be sure. Didn't help. 

It is weird that I saw yesterday but can't see today. I have no idea what might change, I didn't install sth new.

**Comment by thevindu-w** [comment]
If you didn't create a config file with tray_icon=false, it should work. I'll try to re-create the issue on my machine.

**Comment by JFMugen** [comment]
I didn't touch or create any config file :/

**Comment by thevindu-w** [comment]
I re-created the problem in my machine also. That happened when I moved the exe to another partition. Now I can further check what's wrong.
As a temporary solution, **copy**v (not move) the exe file back to where it was working. And then run it there. Although it worked for me, I'm not sure if that works always.

**Comment by JFMugen** [comment]
Either way it is not a huge deal or anything as the program still works great, but I am glad you managed to recreate the issue. Thanks :)

**Comment by thevindu-w** [comment]
@JFMugen tray icon not showing when exe is moved is now fixed in [version 2.3](https://github.com/thevindu-w/clip_share_server/releases/v2.3).
 
> But I just think you should add "Right Click -> Exit" option to the tray icon. I don't think any more than "Exit" is needed.

this is also included in that release.

**Comment by JFMugen** [comment]
Works flawlessly, thanks :)
