### ISSUE TITLE
Are client versions for windows and linux expected?

### ISSUE THREAD

**Issue by paolosezart** [thevindu-w/clip_share_server#27]
This is a very interesting and convenient program. I would like to have client versions for windows and linux arm64 debian (raspberry pi)
Maybe respected developer will make cross-platform client for different OS?

**Comment by thevindu-w** [comment]
I built a desktop client (using java). But I didn't published it yet. If you like to have a desktop client, I'll try to publish it. (It may take a few weeks to get it updated with latest changes and test it.)

**Comment by thevindu-w** [comment]
The desktop client is now available at [https://github.com/thevindu-w/clip_share_client_desktop](https://github.com/thevindu-w/clip_share_client_desktop)

**Comment by paolosezart** [comment]
It's beautiful!

**Comment by thevindu-w** [comment]
I'm planning to build a lightweight client in C rhat does not require java. I plan to have a web GUI for that similar to the Android client. If I make it, I'll notify in this thread.

Since we have a desktop client, I'll close this issue. If you find any issues with the new desktop client, please create an issue in the new repo.

**Comment by thevindu-w** [comment]
A desktop client for ClipShare is available at [https://github.com/thevindu-w/clip_share_desktop/releases](https://github.com/thevindu-w/clip_share_desktop/releases). This supports Linux (amd64 and arm64), Windows, and macOS (Intel and Apple silicon).
